name: Notarize immudb-py

on:
  push:
    branches:
      - master
      - develop

jobs:
  notarize-repository:
    name: Notarize immudb-py repository with cas and vcn
    runs-on: [self-hosted, linux]
    uses: codenotary/notarize-with-cas-and-vcn/.github/workflows/notarize-with-cas-and-vcn.yml@862cb3fbee3fbce20bf0e2fae97ac201c730fe23
    secrets:
      cas-api-key: ${{ secrets.CAS_API_KEY_ATTEST }}
      vcn-api-key: ${{ secrets.CICD_LEDGER1_ACTION_KEY }}
      vcn-host: ${{ secrets.CI_TEST_HOST }}
